### ISSUE TITLE
Filenames and directories with umlauts and accents don't get indexed

### ISSUE THREAD

**Issue by jeena** [subsonic/SubSonic-3.0#286]
Filenames with umlauts and accents don't get indexed, I have this directory:

 `/home/jeena/Music/Yelle/Complètement fou/01 Complètement fou.mp3`

and it never gets indexed. After I changed "è" to "e" it showed up in Subsonic without problems. I had the same problem with german and swedish umlauts like: `ÅÜÄÖß I almost assume all the names have to be ASCII which is kind of weird in 2015.

**Comment by 6pac** [comment]
Sorry, this is the wrong SubSonic. We're not a music player!

**Comment by jeena** [comment]
Oh I'm very sorry.
