### ISSUE TITLE
Missing README.md file

### ISSUE THREAD

**Issue by PeterMortensen** [subsonic/SubSonic-3.0#289]
I miss information about what SubSonic *is*. This could be in a README file (*README.md*). It doesn't have to be very long.

The closest I could find was (http://web.archive.org/web/20130314061901/http://subsonic.wekeroad.com/):

> SubSonic is a super high-fidelity batman utility belt that works up your data access (using LINQ in 3.0), throws in some much-needed utility functions, and generally speeds along your development cycle. 

This is still too generic, I think (what kind of data access? Is it about databases only? What databases? Is MySQL supported?). Context - where does it run? Is it only for .NET? Only on Windows? Does it run on Linux, under .NET Core?

Possible other useful information for a README file:

 * A few examples of where it used could also be useful to illustrate what it does.

 * There is also the question of disambiguation (Is it related George J. Capnias's work - e.g. https://gcapnias.wordpress.com/2009/01/12/subsonic-v3s-t4-templates/? Or is it unrelated?) Searching brings up firearms sites and a music streamer (*"the Subsonic server app where you keep your media"*. https://play.google.com/store/apps/details?id=net.sourceforge.subsonic.androidapp&hl=en_US). 

 * What is the status of the project? Has it been updated since 2009? Is it in hibernation or not? Is it actively used in other projects?

<hr/>

[Epside 196 of .NET Rocks](https://www.dotnetrocks.com/default.aspx?ShowNum=196) is about SubSonic, *"Rob Conery on SubSonic"*. [Direct download URL](https://stream.redcircle.com/episodes/f9fdf008-7f27-476d-98d3-e4fbd55ea4aa/stream.mp3).

**Comment by robconery** [comment]
SubSonic is a pretty old project as the date on the podcast episode kind of indicates. It was created well before GitHub (and Git itself) was even dreamed of and got parked here a long, long time ago.

A few people have pitched in to maintain it as they have projects still running on it :) which is nuts but also kind of fun.

You can consider it not active I suppose. EF is likely a better choice.
